substitutions:
  devicename: esp32_4


esphome:
  name: $devicename
  platform: ESP32
  board: lolin32


wifi:
  ssid: !secret ssid_iot
  password: !secret password_iot
  fast_connect: true
  manual_ip:
    static_ip: 192.168.0.113
    gateway: 192.168.0.1
    subnet: 255.255.255.0

web_server:
  port: 80
api:

logger:
  level: WARN

ota:
  password: !secret ota_password

i2c:
  sda: 21
  scl: 22

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${devicename}_ip"
    ssid:
      name: "${devicename}_ssid"
  - platform: version
    name: "${devicename}_version"


sensor:
#wifi signal
  - platform: wifi_signal
    name: "${devicename}_rssi"
#uptime
  - platform: uptime
    name: "${devicename}_uptime"
#bme280
  - platform: bme280
    temperature:
      name: "${devicename}_temperature"
    pressure:
      name: "${devicename}_pressure"
    humidity:
      name: "${devicename}_humidity"
    address: 0x76

binary_sensor:
  - platform: gpio
    pin: 16
    name: "${devicename}_motion"
    device_class: motion
  - platform: status
    name: "${devicename}_status"
switch:
  - platform: shutdown
    name: "${devicename}_shutdown"
    id: shutdown1
  - platform: restart
    name: "${devicename}_restart"
  - platform: output
    name: "${devicename}_led"
    output: '${devicename}_led'


output:
  - platform: gpio
    pin: 17
    id: '${devicename}_led'
