esphome:
  name: esp32_2
  platform: ESP32
  board: lolin32

wifi:
  ssid: !secret ssid_iot
  password: !secret password_iot
  manual_ip:
    static_ip: 192.168.0.111
    gateway: 192.168.0.1
    subnet: 255.255.255.0

mqtt:
  broker: '192.168.0.27'
  username: 'ha'
  password: 'ha'
  discovery: False
  discovery_retain: False


logger:
  level: WARN

deep_sleep:
  run_duration: 5s
  sleep_duration: 60min


i2c:
  sda: 21
  scl: 22

sensor:
#wifi signal
  - platform: wifi_signal
    name: "esp32_2 WiFi Signal Sensor"
#bme280
  - platform: bme280
    temperature:
      name: "temperature"
    pressure:
      name: "pressure"
    humidity:
      name: "humidity"
    address: 0x76
#battery
  - platform: adc
    pin: 34
    attenuation: 11db
    name: "Spannung Akku"

binary_sensor:
  - platform: status
    name: "esp32_2 Status"

switch:
  - platform: shutdown
    name: "esp32_2 Shutdown"
